name: 'Chromatic'

on:
  pull_request:
    branches:
      - 'develop'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Publish to Chromatic
        run: bunx chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --exit-once-uploaded
      - name: Upload Logs
        uses: actions/upload-artifact@v3
        if: ${{ !cancelled() }}
        with:
          name: external-logs
          path: /home/runner/work/beesoft-components/beesoft-components/**/*.log
